local: ${LOCALHOST:localhost}
spring:
  profiles.active: development
  datasource:
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.hibernate.dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
  application:
    name: core
  cache:
    type: redis
  data:
    redis:
      port: 6379


---
spring:
  config.activate.on-profile: development
  datasource:
    url: jdbc:postgresql://localhost:5432/property
    username: user_name
    password: password
  jpa:
    generate-ddl: true
    show-sql: false


---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://localhost:5432/property
    username: user_name
    password: password
  jpa:
    generate-ddl: true
    show-sql: false

